server:
  port: 8101

spring:
  application:
    name: wsj-auth
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
