server:
  port: 8301
spring:
  application:
    name: wsj-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 开启从注册中心动态创建路由的功能
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: auth_route
          uri: http://localhost:8101 #lb://wsj-auth # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: test_route
          uri: lb://wsj-test # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/wsj/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/oauth/token"


