server:
  port: 8301
spring:
  application:
    name: wsj-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
        routes:
          - id: auth_route
            uri: lb://wsj-auth:8101 # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
            predicates:
              - Path=/auth/**
#      routes:
#      - id: auth-route
#        uri: http://localhost:8101//
#        predicates:
#          - Path=/auth/**
#      - id: message-provider-route
#        uri: lb://message-provider
#        predicates:
#        -Path=/message-provider/**
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://wsj:wsj1065@localhost:8001/register/eureka/

