server:
  port: 8301
spring:
  application:
    name: wsj-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lowerCaseServiceId: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: auth_route
          uri: lb://wsj-auth # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/auth/**
        - id: test_route
          uri: lb://wsj-test # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/wsj/**

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      routes:
#      - id: auth-route
#        uri: http://localhost:8101//
#        predicates:
#          - Path=/auth/**
#      - id: message-provider-route
#        uri: lb://message-provider
#        predicates:
#        -Path=/message-provider/**
#management:
#  endpoint:
#    health:
#      show-details: ALWAYS
#  endpoints:
#    web:
#      exposure:
#        include: health,info,gateway

